'use strict';

const DEFAULT_PRODUCTS = [
{id:'pink-gift-box',name:'بوكس هدايا وردي',cat:'هدايا',price:150000,old:180000,badge:'الأكثر طلبًا',desc:'بوكس أنيق قابل للتخصيص.',image:''},
{id:'rose-touch',name:'مجموعة لمسة وردية',cat:'مكياجات',price:95000,old:null,badge:'جديد',desc:'مجموعة تجريبية للمظهر الناعم.',image:''},
{id:'pearl-set',name:'طقم لؤلؤ زمردة',cat:'اكسسوارات',price:120000,old:145000,badge:'عرض',desc:'إكسسوار ناعم للهدايا والمناسبات.',image:''},
{id:'love-box',name:'صندوق حب صغير',cat:'هدايا',price:85000,old:null,badge:null,desc:'تفصيل بسيط برسالة خاصة.',image:''},
{id:'glow-kit',name:'Glow Kit',cat:'مكياجات',price:110000,old:130000,badge:'عرض',desc:'مجموعة تجريبية يومية.',image:''},
{id:'gold-chain',name:'سلسال ذهبي ناعم',cat:'اكسسوارات',price:135000,old:null,badge:'جديد',desc:'قطعة بسيطة وأنيقة.',image:''},
{id:'surprise-box',name:'مفاجأة زمردة',cat:'هدايا',price:175000,old:null,badge:'مميز',desc:'هدية جاهزة لمناسبة خاصة.',image:''},
{id:'beauty-box',name:'Beauty Box',cat:'مكياجات',price:160000,old:190000,badge:'عرض',desc:'تشكيلة تجريبية فاخرة.',image:''}
];
const WA='963986056357';
const state={lang:localStorage.getItem('zumurda-lang')||'ar', products:loadProducts()};
const T={ar:{home:'الرئيسية',products:'المنتجات',offers:'العروض',about:'عن زمردة',contact:'تواصل',search:'ابحثي عن منتج…',all:'الكل',order:'اطلبي هذا المنتج ↗',details:'عرض التفاصيل',noResults:'ما لقينا منتجات مطابقة.',back:'العودة للمنتجات',orderNow:'اطلبي الآن',category:'التصنيف',price:'السعر',quantity:'الكمية',name:'الاسم الكامل',phone:'رقم الهاتف',city:'المحافظة',address:'العنوان بالتفصيل',notes:'ملاحظات إضافية',send:'إرسال الطلب عبر WhatsApp ↗',required:'تأكدي من تعبئة البيانات بشكل صحيح',delivery:'توصيل إلى كافة الأراضي السورية',wa:'تواصل معنا عبر WhatsApp',instagram:'صفحتنا على Instagram',tiktok:'صفحتنا على TikTok',maps:'موقعنا على الخريطة',language:'Türkçe'},tr:{home:'Ana Sayfa',products:'Ürünler',offers:'Fırsatlar',about:'Zümruda',contact:'İletişim',search:'Ürün ara…',all:'Tümü',order:'Bu ürünü sipariş et ↗',details:'Detayları gör',noResults:'Eşleşen ürün bulunamadı.',back:'Ürünlere dön',orderNow:'Şimdi sipariş ver',category:'Kategori',price:'Fiyat',quantity:'Adet',name:'Ad Soyad',phone:'Telefon',city:'İl',address:'Detaylı adres',notes:'Ek notlar',send:'WhatsApp ile sipariş gönder ↗',required:'Lütfen gerekli alanları doğru doldurun',delivery:'Suriye genelinde teslimat',wa:'WhatsApp ile iletişim',instagram:'Instagram sayfamız',tiktok:'TikTok sayfamız',maps:'Haritada konumumuz',language:'العربية'}};
function loadProducts(){try{const x=JSON.parse(localStorage.getItem('zumurda-products'));return Array.isArray(x)&&x.length?x:DEFAULT_PRODUCTS}catch{return DEFAULT_PRODUCTS}}
function saveProducts(){localStorage.setItem('zumurda-products',JSON.stringify(state.products))}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function money(n){return new Intl.NumberFormat(state.lang==='ar'?'ar-SY':'tr-TR').format(Number(n)||0)+(state.lang==='ar'?' ل.س':' SYP')}
function productUrl(p){return new URL(`product/${encodeURIComponent(p.id)}`,location.href).href}
function t(k){return T[state.lang][k]||k}
function setLanguage(){document.documentElement.lang=state.lang;document.documentElement.dir=state.lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(T[state.lang][k])el.textContent=T[state.lang][k]});const lb=document.querySelector('#langBtn');if(lb)lb.textContent=t('language');localStorage.setItem('zumurda-lang',state.lang)}
function productVisual(p){return p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy">`:`<div class="demo-product-art" aria-label="صورة تجريبية"><span>زمردة</span></div>`}
function render(list=state.products){const grid=document.querySelector('#productGrid');if(!grid)return;grid.innerHTML=list.length?list.map((p,i)=>`<article class="product" data-id="${esc(p.id)}" style="transition-delay:${i*55}ms"><div class="product-img">${p.badge?`<span class="badge">${esc(p.badge)}</span>`:''}${productVisual(p)}</div><div class="product-info"><small>${esc(p.cat)}</small><h3>${esc(p.name)}</h3><div class="price"><b>${money(p.price)}</b>${p.old?`<span class="old">${money(p.old)}</span>`:''}</div><div class="product-actions"><a class="order-btn secondary" href="${esc(productUrl(p))}">${t('details')}</a><button class="order-btn" type="button" data-order="${esc(p.id)}">${t('order')}</button></div></div></article>`).join(''):`<p class="empty-state">${t('noResults')}</p>`;observeProducts()}
function observeProducts(){const items=document.querySelectorAll('.product:not(.visible)');if(!('IntersectionObserver'in window)){items.forEach(x=>x.classList.add('visible'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});items.forEach(x=>io.observe(x))}
function renderFilters(){const f=document.querySelector('#filters');if(!f)return;const cats=[t('all'),...new Set(state.products.map(p=>p.cat))];f.innerHTML=cats.map((c,i)=>`<button type="button" class="${i===0?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('')}
function openOrder(id){const p=state.products.find(x=>x.id===id);const modal=document.querySelector('#orderModal');if(!p||!modal)return;document.querySelector('#productId').value=p.id;document.querySelector('#modalTitle').textContent=p.name;document.querySelector('#modalPrice').textContent=money(p.price);modal.classList.add('open');document.body.style.overflow='hidden';setTimeout(()=>document.querySelector('#customerName')?.focus(),80)}
function closeOrder(){document.querySelector('#orderModal')?.classList.remove('open');document.body.style.overflow=''}
function showToast(text){const el=document.querySelector('#toast');if(!el)return;el.textContent=text;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2800)}
function renderDetail(id){const p=state.products.find(x=>x.id===id),main=document.querySelector('#home');if(!p||!main)return;main.innerHTML=`<section class="section detail-page"><a class="back-link" href="../index.html#products">← ${t('back')}</a><div class="detail-grid"><div class="detail-visual">${productVisual(p)}</div><div class="detail-copy"><div class="section-kicker">${esc(p.cat)}</div><h1>${esc(p.name)}</h1><p>${esc(p.desc)}</p><div class="detail-price">${money(p.price)} ${p.old?`<del>${money(p.old)}</del>`:''}</div><button class="btn primary" data-order="${esc(p.id)}">${t('orderNow')} ↗</button><div class="detail-note">✦ ${t('delivery')}</div></div></div></section>`;setLanguage()}
function init(){setLanguage();const path=location.pathname.replace(/\\/g,'/');const m=path.match(/\/product\/([^/]+)\/?$/);if(m){renderDetail(decodeURIComponent(m[1]));return}renderFilters();render();
const filters=document.querySelector('#filters');filters?.addEventListener('click',e=>{if(!e.target.matches('[data-cat]'))return;filters.querySelectorAll('button').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');const c=e.target.dataset.cat;render(c===t('all')?state.products:state.products.filter(p=>p.cat===c))});
document.querySelector('#search')?.addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();render(state.products.filter(p=>`${p.name} ${p.cat} ${p.desc}`.toLowerCase().includes(q)))});
document.addEventListener('click',e=>{const id=e.target?.dataset?.order;if(id)openOrder(id)});
document.querySelector('#closeModal')?.addEventListener('click',closeOrder);document.querySelector('#orderModal')?.addEventListener('click',e=>{if(e.target.id==='orderModal')closeOrder()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeOrder()});
document.querySelector('#orderForm')?.addEventListener('submit',e=>{e.preventDefault();const p=state.products.find(x=>x.id===document.querySelector('#productId').value);if(!p)return;const vals=Object.fromEntries(new FormData(e.currentTarget).entries());if(!vals.name?.trim()||!vals.phone?.trim()||!vals.city?.trim()||!vals.address?.trim()||!/^[0-9+()\-\s]{7,20}$/.test(vals.phone.trim())){showToast(t('required'));return}const qty=Math.max(1,parseInt(vals.qty,10)||1);const msg=`🌸 طلب جديد — زمردة\n🎁 المنتج: ${p.name}\n💰 السعر: ${money(p.price)}\n🔢 الكمية: ${qty}\n🔗 رابط المنتج: ${productUrl(p)}\n👤 الاسم: ${vals.name.trim()}\n📱 الهاتف: ${vals.phone.trim()}\n📍 المحافظة: ${vals.city.trim()}\n🏠 العنوان: ${vals.address.trim()}\n📝 ملاحظات: ${vals.notes?.trim()||'لا يوجد'}`;window.open(`https://wa.me/${WA}?text=${encodeURIComponent(msg)}`,'_blank','noopener,noreferrer');closeOrder()});
document.querySelector('#langBtn')?.addEventListener('click',()=>{state.lang=state.lang==='ar'?'tr':'ar';setLanguage();renderFilters();render()});
document.querySelector('#menuBtn')?.addEventListener('click',()=>document.querySelector('.nav')?.classList.toggle('menu-open'));
document.querySelectorAll('.finder-row [data-finder]').forEach(b=>b.addEventListener('click',()=>{const map={love:'pink-gift-box',friend:'pearl-set',occasion:'surprise-box'},p=state.products.find(x=>x.id===map[b.dataset.finder]);const r=document.querySelector('#finderResult');if(p&&r)r.innerHTML=`اقتراح زمردة لكِ: <b>${esc(p.name)}</b> — ${money(p.price)} <button class="order-btn" type="button" data-order="${esc(p.id)}">${t('orderNow')}</button>`}));
const progress=document.querySelector('.progress'),nav=document.querySelector('.nav');function scrollUI(){const h=document.documentElement;progress&&(progress.style.width=`${h.scrollHeight>h.clientHeight?(h.scrollTop/(h.scrollHeight-h.clientHeight))*100:0}%`);nav?.classList.toggle('scrolled',h.scrollTop>12)}window.addEventListener('scroll',scrollUI,{passive:true});scrollUI();
if('IntersectionObserver'in window){const ro=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');ro.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>ro.observe(x))}else document.querySelectorAll('.reveal').forEach(x=>x.classList.add('visible'))}
init();
